### PR TITLE
Inital dockerfile, docker-compose to run basic Django server

### PR DESCRIPTION
**Pull request by harsh4870**
Initial Dockerfile, docker-compose to run Basic Django server

docker command to build image:

`docker build --no-cache -t ultimate-social:v1 .`

**else** 

`docker-compose up -d`

### CODE REVIEW

**Comment by gd03champ** [comment]
Hi,
Could you please consider changing the line from `pip install -r requirements.txt && pip install mysqlclient` to `pip install -r requirements.txt` in `Dockerfile` as it would adapt the last commit.
also can we bring in `.env` variables into `docker-compose.yaml` ?

**Comment by harsh4870** [comment]
Hi there, 

Thanks for the suggestion, will try to update & push by the EOD.

**Comment by harsh4870** [comment]
@gd03champ  @vasani-arpit  Feel free to give it try, update the Docker and compose a file.

**Comment by vasani-arpit** [comment]
LGTM

**Pull request merged**
